/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectojd;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class ConsultaEspecifica extends javax.swing.JFrame {
 

    /**
     * Creates new form ConsultaEspecifica
     */
    public ConsultaEspecifica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        btnconsultardatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtcurso = new javax.swing.JTextField();
        txtinstitucion = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        txtinteligencia = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btneliminar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtnumeroid = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(215678898, 2147483647));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("HISTORIAL ESPECIFICO DE ESTUDIANTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 0, 430, 25);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("RESULTADO DE PRUEBAS REALIZADAS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 400, 380, 20);

        btnregresar.setText("REGRESAR");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregresar);
        btnregresar.setBounds(490, 510, 100, 23);

        btnconsultardatos.setText("CONSULTAR");
        btnconsultardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultardatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultardatos);
        btnconsultardatos.setBounds(490, 70, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("<html>Digite Numero de Identidad de estudiante para BUSCAR INFORMACIÓN DETALLADA</html>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 420, 30);

        txtnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnuActionPerformed(evt);
            }
        });
        getContentPane().add(txtnu);
        txtnu.setBounds(370, 40, 150, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("NOMBRES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 60, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("APELLIDOS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 69, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("EDAD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 34, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("CURSO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 250, 42, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("INSTITUCION");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 280, 78, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("CIUDAD");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 130, 48, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("DIRECCION");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 190, 80, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("TELEFONO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 170, 60, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("USUARIO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 230, 56, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("CONTRASEÑA");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 260, 82, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 51));
        jLabel14.setText("DATOS PERSONALES");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 60, 270, 40);
        getContentPane().add(txtnombres);
        txtnombres.setBounds(70, 130, 160, 20);

        txtapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidosActionPerformed(evt);
            }
        });
        getContentPane().add(txtapellidos);
        txtapellidos.setBounds(80, 160, 160, 20);
        getContentPane().add(txtedad);
        txtedad.setBounds(60, 220, 40, 20);
        getContentPane().add(txtcurso);
        txtcurso.setBounds(60, 250, 40, 20);
        getContentPane().add(txtinstitucion);
        txtinstitucion.setBounds(90, 280, 200, 20);

        txtciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciudadActionPerformed(evt);
            }
        });
        getContentPane().add(txtciudad);
        txtciudad.setBounds(320, 130, 110, 20);
        getContentPane().add(txttelefono);
        txttelefono.setBounds(320, 170, 110, 20);
        getContentPane().add(txtdireccion);
        txtdireccion.setBounds(410, 190, 140, 20);
        getContentPane().add(txtusuario);
        txtusuario.setBounds(370, 230, 150, 20);
        getContentPane().add(txtcontraseña);
        txtcontraseña.setBounds(390, 260, 150, 20);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("ACTIVIDAD N-1");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 470, 90, 20);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("P1");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(115, 438, 20, 20);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("P2");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(150, 440, 20, 13);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("P3");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(180, 440, 20, 20);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("P4");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(205, 438, 20, 20);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("P5");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(235, 438, 20, 20);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("P6");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(260, 440, 20, 20);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("P7");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(295, 444, 20, 13);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("P8");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(325, 438, 20, 20);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("P9");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(363, 438, 20, 20);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("P10");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(402, 438, 20, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(117, 467, 20, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(147, 467, 20, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(177, 467, 20, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(207, 467, 20, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(237, 467, 18, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(265, 467, 19, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(294, 467, 20, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(363, 467, 19, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(400, 467, 22, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(324, 467, 21, 20);

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar);
        btnlimpiar.setBounds(490, 100, 90, 23);

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar);
        btnmodificar.setBounds(490, 140, 100, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(10, 396, 687, 10);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 204));
        jLabel26.setText("I.M IDENTIFICADA");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(70, 330, 170, 15);

        txtinteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinteligenciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtinteligencia);
        txtinteligencia.setBounds(10, 354, 240, 30);
        getContentPane().add(txtdescripcion);
        txtdescripcion.setBounds(330, 360, 250, 31);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 204));
        jLabel27.setText(" DESCRIPCION DE INCLINACION I.M");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(330, 340, 216, 15);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 31, 687, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 500, 687, 10);

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar);
        btneliminar.setBounds(490, 120, 100, 23);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 204));
        jLabel28.setText("NUMERO DE IDENTIFICACION");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(10, 190, 175, 15);
        getContentPane().add(txtnumeroid);
        txtnumeroid.setBounds(190, 190, 130, 20);

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(510, 0, 70, 30);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Desktop\\cerebros-creativos.jpg")); // NOI18N
        jLabel29.setMaximumSize(new java.awt.Dimension(900, 800));
        jLabel29.setMinimumSize(new java.awt.Dimension(900, 800));
        jLabel29.setPreferredSize(new java.awt.Dimension(900, 900));
        jLabel29.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel29);
        jLabel29.setBounds(0, 0, 10040, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultardatosActionPerformed
        // consulta datos historial especifico de cada estudiante

            try
           {
           String criterio=txtnu.getText();
           conexionBD conexion=new conexionBD();
           Statement sentencia=conexion.getconexion().createStatement();
      
           ResultSet resultado=sentencia.executeQuery("Select * from Registro where(Numero_Identificacion='"+criterio+"')");
           while(resultado.next())
           {
           txtnombres.setText(""+resultado.getString("Nombres"));
           txtapellidos.setText(""+resultado.getString("Apellidos"));
           txtnumeroid.setText(""+resultado.getString("Numero_Identificacion"));
           txtedad.setText(""+resultado.getString("Edad"));
           txtcurso.setText(""+resultado.getString("Curso"));
           txtinstitucion.setText(""+resultado.getString("Institucion"));
           txtciudad.setText(""+resultado.getString("ciudad"));
           txtdireccion.setText(""+resultado.getString("Direccion"));
           txttelefono.setText(""+resultado.getString("Telefono"));
           txtusuario.setText(""+resultado.getString("Usuario"));
           txtcontraseña.setText(""+resultado.getString("contraseña"));
           
       }
           resultado.close();
           conexion.getconexion().close();
       }
        catch(SQLException e)
       {
       JOptionPane.showMessageDialog(this,"Error :"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
       }
            
       try
        {
            String criterio=txtnu.getText();
            conexionBD conexion=new conexionBD();
            Statement sentencia=conexion.getconexion().createStatement();
            ResultSet resultado=sentencia.executeQuery("Select * from Test where (Numero_Identificacion='"+criterio+"')");

            while(resultado.next())
            {
                txtinteligencia.setText(""+resultado.getString("Tipo_Inteligencia"));
                txtdescripcion.setText(""+resultado.getString("Tipo_Aprendizaje"));
            }
            resultado.close();
            conexion.getconexion().close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error :"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnconsultardatosActionPerformed

    private void txtnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnuActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // Regresa a la pagina de consulta historial general

        Consultarhistorial tres=new Consultarhistorial();
        tres.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    private void txtapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosActionPerformed

    private void txtciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        //DEJA  EN BLANCO CAMPOS DE TEXTO,PARA PODER GEENRAR INFORMACION DIFERENTE.

        txtnu.setText("");
        txtnombres.setText("");
        txtapellidos.setText("");
        txtnumeroid.setText("");
        txtedad.setText("");
        txtcurso.setText("");
        txtinstitucion.setText("");
        txtciudad.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtusuario.setText("");
        txtcontraseña.setText("");
        txtinteligencia.setText("");
        txtdescripcion.setText("");
        
              
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // Modifica directamente datos registrados por el estudiante.
   
        try{
            conexionBD conexion=new conexionBD();
            String instruccion="Update Registro set Nombres=?,Apellidos=?,Numero_Identificacion=?,Edad=?,Curso=?,Institucion=?,Ciudad=?,Direccion=?,Telefono=?,Usuario=?,Contraseña=? where Numero_Identificacion="+txtnu.getText()+"";
            conexion.sentencia=conexion.getconexion().prepareStatement(instruccion);
            conexion.sentencia.setString(1, txtnombres.getText());
            conexion.sentencia.setString(2, txtapellidos.getText());
            conexion.sentencia.setString(3, txtnumeroid.getText());
            conexion.sentencia.setString(4, txtedad.getText());
            conexion.sentencia.setString(5, txtcurso.getText());
            conexion.sentencia.setString(6, txtinstitucion.getText());
            conexion.sentencia.setString(7, txtciudad.getText());
            conexion.sentencia.setString(8, txtdireccion.getText());
            conexion.sentencia.setString(9, txttelefono.getText());
            conexion.sentencia.setString(10, txtusuario.getText());
            conexion.sentencia.setString(11,txtcontraseña.getText());
            conexion.sentencia.execute();
            JOptionPane.showMessageDialog(this,"Su Registro ha sido Modificado","Informacion",JOptionPane.INFORMATION_MESSAGE);
            conexion.getconexion().close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error SQL"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // Elimina Registro.

        try
        {
            conexionBD conexion=new conexionBD();
            String instruccion="Delete Registro where Numero_Identificacion="+txtnu.getText()+"";
            conexion.sentencia=conexion.getconexion().prepareStatement(instruccion);
            conexion.sentencia.execute();
            JOptionPane.showMessageDialog(this,"Registro Eliminado","Informacion",JOptionPane.INFORMATION_MESSAGE);
            conexion.getconexion().close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error SQL"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtinteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinteligenciaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtinteligenciaActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // boton de salir
        
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspecifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaEspecifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultardatos;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtinstitucion;
    private javax.swing.JTextField txtinteligencia;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnu;
    private javax.swing.JTextField txtnumeroid;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
