/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectojd;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Consultarhistorial extends javax.swing.JFrame {
ConsultaEspecifica dos=new ConsultaEspecifica();
    /**
     * Creates new form Consultarhistorial
     */
    public Consultarhistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnconsultagral = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultahistorial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnespecifica = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnconsultagral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnconsultagral.setForeground(new java.awt.Color(0, 0, 255));
        btnconsultagral.setText("CONSULTA GENEREAL DE ESTUDIANTES");
        btnconsultagral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultagralActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultagral);
        btnconsultagral.setBounds(27, 113, 270, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("HISTORIAL GENEREAL DE ESTUDIANTES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 390, 50);

        consultahistorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        consultahistorial.setForeground(new java.awt.Color(0, 0, 255));
        consultahistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Edad", "Curso", "Institucion", "Ciudad", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(consultahistorial);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 196, 520, 114);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Presione Click en CONSULTAR, para obtener Historial Especifico del estudiante.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 350, 500, 15);

        btnespecifica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnespecifica.setForeground(new java.awt.Color(0, 0, 255));
        btnespecifica.setText("CONSULTAR");
        btnespecifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnespecificaActionPerformed(evt);
            }
        });
        getContentPane().add(btnespecifica);
        btnespecifica.setBounds(395, 390, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Desktop\\cerebros-creativos.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 550, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultagralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultagralActionPerformed
        // consulta estudiantes base de datos
        
        DefaultTableModel consul=new DefaultTableModel();
        this.consultahistorial.setModel(consul);
        conexionBD conexion=new conexionBD();
        Statement sentencia;
        try{
           sentencia=conexion.getconexion().createStatement();
            ResultSet resultado=sentencia.executeQuery("Select * from Registro");
            ResultSetMetaData campos = resultado.getMetaData();
            int catidadColumnas=campos.getColumnCount();
            for(int i=1;i<=catidadColumnas; i++)
            {
                consul.addColumn(campos.getColumnLabel(i));
            }
            while(resultado.next())
            {
                Object[] fila=new Object[catidadColumnas];
                for (int i=0;i<catidadColumnas;i++)
                {
                    fila[i]=resultado.getObject(i+1);
                }
                consul.addRow(fila);
            }
            resultado.close();
            conexion.getconexion().close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Error SQL"+e,"Informacion",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error"+e,"Informacion",JOptionPane.INFORMATION_MESSAGE);
        }
    }                                             

    
    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {                                          
       Registro uno=new Registro();
        uno.setVisible(true);
        dispose();
    
    }//GEN-LAST:event_btnconsultagralActionPerformed

    private void btnespecificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnespecificaActionPerformed
        // Me lleva directamente a la pagina de historial especifico
      
        dos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnespecificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultarhistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultarhistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultarhistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultarhistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultarhistorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultagral;
    private javax.swing.JButton btnespecifica;
    private javax.swing.JTable consultahistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
