/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectojd;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class InicioSesion extends javax.swing.JFrame {
   Test cinco=new Test();
  PrincipalAdministrador seis=new PrincipalAdministrador ();
    
    Ayuda cuatro=new Ayuda();
    Registro dos= new Registro();
    
     
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btninicio = new javax.swing.JButton();
        lblcontraseña = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        txtusuario = new javax.swing.JTextField();
        btnregistro = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnayuda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N

        jPanel1.setLayout(null);

        btninicio.setBackground(new java.awt.Color(255, 255, 255));
        btninicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btninicio.setForeground(new java.awt.Color(51, 0, 204));
        btninicio.setText("INICIAR SESION");
        btninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninicioActionPerformed(evt);
            }
        });
        jPanel1.add(btninicio);
        btninicio.setBounds(400, 400, 190, 25);

        lblcontraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcontraseña.setForeground(new java.awt.Color(51, 0, 204));
        lblcontraseña.setText("CONTRASEÑA");
        jPanel1.add(lblcontraseña);
        lblcontraseña.setBounds(20, 260, 112, 22);

        lblusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(51, 0, 204));
        lblusuario.setText("USUARIO");
        jPanel1.add(lblusuario);
        lblusuario.setBounds(50, 200, 100, 20);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(149, 255, 169, 30);

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario);
        txtusuario.setBounds(149, 204, 170, 30);

        btnregistro.setBackground(new java.awt.Color(255, 255, 255));
        btnregistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnregistro.setForeground(new java.awt.Color(51, 0, 204));
        btnregistro.setText("REGISTRARSE");
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistro);
        btnregistro.setBounds(450, 90, 140, 25);

        lbltitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(0, 0, 204));
        lbltitulo.setText("Software Educativo Inteligencias-Múltiples");
        jPanel1.add(lbltitulo);
        lbltitulo.setBounds(80, -10, 520, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("<html>RECUERDE,Su CONTRASEÑA es su NÚMERO DE IDENTIFICACIÓN.</html1>");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 250, 190, 88);

        btnayuda.setBackground(new java.awt.Color(255, 255, 255));
        btnayuda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnayuda.setForeground(new java.awt.Color(51, 0, 204));
        btnayuda.setText("AYUDA");
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        jPanel1.add(btnayuda);
        btnayuda.setBounds(10, 450, 100, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Desktop\\cerebros-creativos.jpg")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel3.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -40, 1080, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninicioActionPerformed
        // Validacion de inicio de sesion
        
                                       
       String Usuario, Contrasena = null;
       Usuario=txtusuario.getText().trim(); 
       Contrasena=password.getText().trim();
    
       String UsuarioBD=null;
       String ContrasenaBD=null;
   
    
        
        try
       {
           String criterio=txtusuario.getText();
           conexionBD conexion=new conexionBD();
           Statement sentencia=conexion.getconexion().createStatement();
           ResultSet resultado=sentencia.executeQuery("Select * from Administrador where(Usuario='"+criterio+"')");
          
           while(resultado.next())
           {
               
           txtusuario.setText(""+resultado.getString("Usuario"));           
           password.setText(""+resultado.getString("Contraseña"));
           
           JOptionPane.showMessageDialog(null, "Datos de Usuario VALIDOS");
           JOptionPane.showMessageDialog(null, "Bienvenido al sistema");
           seis.setVisible(true);
                        dispose();
           }  
                    
                    resultado.close();
           conexion.getconexion().close();
                    
                    if(Usuario=="admon" && Contrasena=="123456789"){
                     
           }else{
            JOptionPane.showMessageDialog(null, "Nombre de Usuario o Contraseña Incorrecto2");
           }
       }
        catch(SQLException e)
       {
       JOptionPane.showMessageDialog(this,"Error :"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
       }
      
    try{ 
       
        String INICIOSESION="SELECT * FROM Registro WHERE " + " Usuario ='" + Usuario + " ' AND " + " Contraseña= '"+ Contrasena +"'";
       
        
        conexionBD conexion=new conexionBD();
        Statement sentencia=conexion.getconexion().createStatement();
        ResultSet resultado=sentencia.executeQuery(INICIOSESION);
       
        String encontrar= "N";
        while(resultado.next())
        {
               encontrar = "S";  
               UsuarioBD = resultado.getString("Usuario");
               ContrasenaBD = resultado.getString("Contraseña");
        }
           
        if( Usuario.length()== 0 ) { 
            JOptionPane.showMessageDialog(this,"El campo Usuario no puede estar vacio","Error",JOptionPane.ERROR_MESSAGE); 
        }else{
            if( Contrasena.length()== 0 ) { 
                JOptionPane.showMessageDialog(this,"El campo Contraseña no puede estar vacio","Error",JOptionPane.ERROR_MESSAGE); 
        
            }else{
                if(encontrar.compareTo("S")==0){ 
                    
                    if(UsuarioBD.compareToIgnoreCase(Usuario)==0 ){
                    if(ContrasenaBD.compareToIgnoreCase(Contrasena)==0 ){
                    JOptionPane.showMessageDialog(null, "Datos de Usuario VALIDOS");
                    JOptionPane.showMessageDialog(null, "Bienvenido al sistema");             
                             cinco.setVisible(true);
                                dispose();
                            }
                       }else{
                        JOptionPane.showMessageDialog(null, "Nombre de Usuario o Contraseña Incorrecto1");
                    }
                    
                    
                }   
                }
                }      
                   }
       catch(SQLException e){
           
            JOptionPane.showMessageDialog(this,"Error :"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btninicioActionPerformed

    
    
    

            

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // Validacion contraseña
    

    
    }//GEN-LAST:event_passwordActionPerformed

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        //ME DIRIGE A LA PAGINA DE REGISTRO
       dos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregistroActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed
        // Nos lleva ala pagian de ayuda
      cuatro.setVisible(true);
        dispose();
                
    }//GEN-LAST:event_btnayudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btninicio;
    private javax.swing.JButton btnregistro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblusuario;
    public static javax.swing.JPasswordField password;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    

}
