/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectojd;





/**
 *
 * @author usuario
 */
public class PrincipalAdministrador extends javax.swing.JFrame {
    
Consultarhistorial siete=new Consultarhistorial ();
Actividades abrir=new Actividades ();
    private String URL;

    /**
     * Creates new form PrincipalAdministrador
     */
    public PrincipalAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnhistorial = new javax.swing.JButton();
        btnactividades = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("<html>SISTEMA INFORMACIÓN ESTUDIANTES</html>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 340, 60);

        btnhistorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhistorial.setForeground(new java.awt.Color(0, 51, 204));
        btnhistorial.setText("HISTORIAL ESTUDIANTES");
        btnhistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnhistorial);
        btnhistorial.setBounds(30, 90, 220, 23);

        btnactividades.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnactividades.setForeground(new java.awt.Color(0, 51, 204));
        btnactividades.setText("SUBIR ACTIVIDADES");
        btnactividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactividadesActionPerformed(evt);
            }
        });
        jPanel1.add(btnactividades);
        btnactividades.setBounds(30, 140, 200, 23);

        btnreportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnreportes.setForeground(new java.awt.Color(0, 51, 204));
        btnreportes.setText("REPORTE");
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnreportes);
        btnreportes.setBounds(50, 190, 140, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Desktop\\cerebros-creativos.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(9, -10, 360, 280);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 963, 509);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistorialActionPerformed
        // ME LLEVA DIRECTAMENTE LA PAGINA PRINCIPLA DE HISTORIAL GENERAL
          siete.setVisible(true);
          dispose();
    }//GEN-LAST:event_btnhistorialActionPerformed

    private void btnactividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactividadesActionPerformed
        // TODO add your handling code here:
        abrir.setVisible(true);
          dispose();
    }//GEN-LAST:event_btnactividadesActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        conexionBD r =  new conexionBD();
        r.generarReporte();           
        
        
       
    }//GEN-LAST:event_btnreportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactividades;
    private javax.swing.JButton btnhistorial;
    private javax.swing.JButton btnreportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
