/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectojd;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombres = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lbledad = new javax.swing.JLabel();
        lblcurso = new javax.swing.JLabel();
        blbinstitucion = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtcurso = new javax.swing.JTextField();
        txtinstitucion = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnvolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblregistro = new javax.swing.JLabel();
        txtciudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnumeroid = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblnombres.setForeground(new java.awt.Color(0, 102, 255));
        lblnombres.setText("NOMBRES");
        getContentPane().add(lblnombres);
        lblnombres.setBounds(10, 54, 48, 14);

        lblapellidos.setForeground(new java.awt.Color(0, 102, 255));
        lblapellidos.setText("APELLIDOS");
        getContentPane().add(lblapellidos);
        lblapellidos.setBounds(10, 95, 54, 14);

        lbledad.setForeground(new java.awt.Color(0, 102, 255));
        lbledad.setText("EDAD");
        getContentPane().add(lbledad);
        lbledad.setBounds(10, 175, 27, 14);

        lblcurso.setForeground(new java.awt.Color(0, 102, 255));
        lblcurso.setText("CURSO");
        getContentPane().add(lblcurso);
        lblcurso.setBounds(10, 212, 35, 14);

        blbinstitucion.setForeground(new java.awt.Color(0, 102, 255));
        blbinstitucion.setText("INSTITUCION");
        getContentPane().add(blbinstitucion);
        blbinstitucion.setBounds(10, 253, 66, 14);

        lblusuario.setForeground(new java.awt.Color(0, 102, 255));
        lblusuario.setText("USUARIO");
        getContentPane().add(lblusuario);
        lblusuario.setBounds(10, 398, 46, 14);

        lblcontraseña.setForeground(new java.awt.Color(0, 102, 255));
        lblcontraseña.setText("CONTRASEÑA");
        getContentPane().add(lblcontraseña);
        lblcontraseña.setBounds(10, 436, 68, 14);

        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombres);
        txtnombres.setBounds(100, 51, 347, 20);

        txtapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidosActionPerformed(evt);
            }
        });
        getContentPane().add(txtapellidos);
        txtapellidos.setBounds(100, 92, 347, 20);

        txtedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtedadActionPerformed(evt);
            }
        });
        getContentPane().add(txtedad);
        txtedad.setBounds(100, 169, 70, 20);

        txtcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcursoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcurso);
        txtcurso.setBounds(100, 209, 70, 20);

        txtinstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinstitucionActionPerformed(evt);
            }
        });
        getContentPane().add(txtinstitucion);
        txtinstitucion.setBounds(100, 247, 242, 20);

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario);
        txtusuario.setBounds(100, 395, 253, 20);

        txtcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtcontraseña);
        txtcontraseña.setBounds(100, 433, 193, 20);

        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("CIUDAD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 288, 66, 27);

        lbldireccion.setForeground(new java.awt.Color(0, 102, 255));
        lbldireccion.setText("DIRECCION");
        getContentPane().add(lbldireccion);
        lbldireccion.setBounds(10, 329, 57, 14);

        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("TELEFONO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 367, 52, 14);

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtdireccion);
        txtdireccion.setBounds(100, 326, 242, 20);

        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txttelefono);
        txttelefono.setBounds(100, 364, 103, 20);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("<html>Presione CLICK aquí  para acceder a la página de inicio de sesion</html>");

        btnvolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(0, 102, 255));
        btnvolver.setText("IR A INICIO DE SESION");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnvolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 499, 520, 40);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));

        lblregistro.setBackground(new java.awt.Color(255, 204, 255));
        lblregistro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblregistro.setForeground(new java.awt.Color(0, 0, 255));
        lblregistro.setText("REGISTRO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblregistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 20, 180, 20);

        txtciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciudadActionPerformed(evt);
            }
        });
        getContentPane().add(txtciudad);
        txtciudad.setBounds(100, 291, 192, 20);

        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("NUMERO DE IDENTIFICACION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 133, 146, 14);

        txtnumeroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroidActionPerformed(evt);
            }
        });
        getContentPane().add(txtnumeroid);
        txtnumeroid.setBounds(166, 130, 182, 20);

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 102, 255));
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(233, 464, 110, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Desktop\\cerebros-creativos.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 0, 600, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // GUARDAR DATOS INSERTADOS EN LA BASE DE DATOS
       
        try
        {
            conexionBD conexion=new conexionBD();
             String Numero_Identificacion=txtnumeroid.getText();
            String Nombres=txtnombres.getText();
            String Apellidos=txtapellidos.getText();
            String Institucion=txtinstitucion.getText();
            String Edad=txtedad.getText();
            String Curso=txtcurso.getText();
            String Ciudad=txtciudad.getText();
            String Direccion=txtdireccion.getText();
            String Telefono=txttelefono.getText();
            String Usuario=txtusuario.getText();
            String Contraseña=txtcontraseña.getText();
            String instruccion="Insert into Registro values(?,?,?,?,?,?,?,?,?,?,?)";
            conexion.sentencia=conexion.getconexion().prepareStatement(instruccion);
            conexion.sentencia.setString(1, Numero_Identificacion);
            conexion.sentencia.setString(2, Nombres);
            conexion.sentencia.setString(3, Apellidos);
            conexion.sentencia.setString(4, Institucion);
            conexion.sentencia.setString(5, Edad);
            conexion.sentencia.setString(6, Curso);
            conexion.sentencia.setString(7, Ciudad);
            conexion.sentencia.setString(8, Direccion);
            conexion.sentencia.setString(9, Telefono);
            conexion.sentencia.setString(10, Usuario);
            conexion.sentencia.setString(11, Contraseña);
            conexion.sentencia.execute();
            JOptionPane.showMessageDialog(this,"Registro insertado","Informacion",JOptionPane.INFORMATION_MESSAGE);
            conexion.getconexion().close();
            
             }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error SQL"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtcontraseñaActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // ME DIRIGE A LA PAGINA  INICIO DE SESION
        InicioSesion uno=new InicioSesion();
        uno.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed
        
       
    }//GEN-LAST:event_txtnombresActionPerformed

    private void txtapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtapellidosActionPerformed

    private void txtnumeroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroidActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnumeroidActionPerformed

    private void txtedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtedadActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtedadActionPerformed

    private void txtcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcursoActionPerformed

    private void txtinstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinstitucionActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtinstitucionActionPerformed

    private void txtciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciudadActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtciudadActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_txtusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbinstitucion;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lbledad;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblregistro;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtinstitucion;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnumeroid;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
