/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectojd;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Test extends javax.swing.JFrame {
Menu di=new Menu();
Menu1 di1=new Menu1();
   
    
   String Taprendizaje1="AUDITIVO";
   String Taprendizaje2="VISUAL";
   String Taprendizaje3="KINESTESICO";
   String pregunta17;
   String pregunta18;
   String pregunta19;
   String pregunta20;
     
   //Preguntas
    Pregunta pregunta1 = new Pregunta("Pregunta1","Linguistica","C");
    Pregunta pregunta2 = new Pregunta("Pregunta2","Linguistica","D");
    Pregunta pregunta3 = new Pregunta("Pregunta3","Matematica","D");
    Pregunta pregunta4 = new Pregunta("Pregunta4","Matematica","C");
    Pregunta pregunta5 = new Pregunta("Pregunta5","Linguistica","C");
    Pregunta pregunta6 = new Pregunta("Pregunta6","Linguistica","C");
    Pregunta pregunta7 = new Pregunta("Pregunta7","Matematica","B");
    Pregunta pregunta8 = new Pregunta("Pregunta8","Matematica","A");
    Pregunta pregunta9 = new Pregunta("Pregunta9","Linguistica","D");
    Pregunta pregunta10 = new Pregunta("Pregunta10","Linguistica","B");
    Pregunta pregunta11 = new Pregunta("Pregunta11","Matematica","C");
    Pregunta pregunta12 = new Pregunta("Pregunta12","Matematica","B");
    Pregunta pregunta13 = new Pregunta("Pregunta13","Linguistica","A");
    Pregunta pregunta14 = new Pregunta("Pregunta14","Linguistica","D");
    Pregunta pregunta15 = new Pregunta("Pregunta15","Matematica","A");
    Pregunta pregunta16 = new Pregunta("Pregunta16","Matematica","B");
   
   
    private int respuetasLinguistica = 0;
    private int respuetasMatematicas = 0;
    
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pre1 = new javax.swing.ButtonGroup();
        pre2 = new javax.swing.ButtonGroup();
        pre3 = new javax.swing.ButtonGroup();
        pre4 = new javax.swing.ButtonGroup();
        pre5 = new javax.swing.ButtonGroup();
        pre6 = new javax.swing.ButtonGroup();
        pre7 = new javax.swing.ButtonGroup();
        pre8 = new javax.swing.ButtonGroup();
        pre9 = new javax.swing.ButtonGroup();
        pre10 = new javax.swing.ButtonGroup();
        pre11 = new javax.swing.ButtonGroup();
        pre12 = new javax.swing.ButtonGroup();
        pre13 = new javax.swing.ButtonGroup();
        pre14 = new javax.swing.ButtonGroup();
        pre15 = new javax.swing.ButtonGroup();
        pre16 = new javax.swing.ButtonGroup();
        pre17 = new javax.swing.ButtonGroup();
        pre18 = new javax.swing.ButtonGroup();
        pre19 = new javax.swing.ButtonGroup();
        pre20 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblmensaje1 = new javax.swing.JLabel();
        ra1 = new javax.swing.JRadioButton();
        ra2 = new javax.swing.JRadioButton();
        ra3 = new javax.swing.JRadioButton();
        ra4 = new javax.swing.JRadioButton();
        ra5 = new javax.swing.JRadioButton();
        lblpregunta2 = new javax.swing.JLabel();
        ra6 = new javax.swing.JRadioButton();
        ra7 = new javax.swing.JRadioButton();
        ra8 = new javax.swing.JRadioButton();
        ra9 = new javax.swing.JRadioButton();
        ra10 = new javax.swing.JRadioButton();
        ra11 = new javax.swing.JRadioButton();
        lblpregunta3 = new javax.swing.JLabel();
        ra12 = new javax.swing.JRadioButton();
        ra13 = new javax.swing.JRadioButton();
        ra14 = new javax.swing.JRadioButton();
        ra15 = new javax.swing.JRadioButton();
        lblpregunta4 = new javax.swing.JLabel();
        ra16 = new javax.swing.JRadioButton();
        ra17 = new javax.swing.JRadioButton();
        ra18 = new javax.swing.JRadioButton();
        ra19 = new javax.swing.JRadioButton();
        lblpregunta5 = new javax.swing.JLabel();
        ra20 = new javax.swing.JRadioButton();
        ra21 = new javax.swing.JRadioButton();
        ra22 = new javax.swing.JRadioButton();
        ra23 = new javax.swing.JRadioButton();
        lblpregunta6 = new javax.swing.JLabel();
        ra24 = new javax.swing.JRadioButton();
        ra25 = new javax.swing.JRadioButton();
        ra26 = new javax.swing.JRadioButton();
        ra27 = new javax.swing.JRadioButton();
        lblpregunta7 = new javax.swing.JLabel();
        ra28 = new javax.swing.JRadioButton();
        ra29 = new javax.swing.JRadioButton();
        ra30 = new javax.swing.JRadioButton();
        ra31 = new javax.swing.JRadioButton();
        lblpregunta8 = new javax.swing.JLabel();
        ra32 = new javax.swing.JRadioButton();
        ra33 = new javax.swing.JRadioButton();
        ra34 = new javax.swing.JRadioButton();
        ra35 = new javax.swing.JRadioButton();
        lblpregunta9 = new javax.swing.JLabel();
        ra36 = new javax.swing.JRadioButton();
        ra37 = new javax.swing.JRadioButton();
        ra38 = new javax.swing.JRadioButton();
        ra39 = new javax.swing.JRadioButton();
        ra40 = new javax.swing.JRadioButton();
        lblpregunta10 = new javax.swing.JLabel();
        ra41 = new javax.swing.JRadioButton();
        ra42 = new javax.swing.JRadioButton();
        ra43 = new javax.swing.JRadioButton();
        ra44 = new javax.swing.JRadioButton();
        lblpregunta11 = new javax.swing.JLabel();
        ra45 = new javax.swing.JRadioButton();
        ra46 = new javax.swing.JRadioButton();
        ra47 = new javax.swing.JRadioButton();
        ra48 = new javax.swing.JRadioButton();
        lblpregunta12 = new javax.swing.JLabel();
        ra49 = new javax.swing.JRadioButton();
        ra50 = new javax.swing.JRadioButton();
        ra51 = new javax.swing.JRadioButton();
        ra52 = new javax.swing.JRadioButton();
        lblpregunta13 = new javax.swing.JLabel();
        ra53 = new javax.swing.JRadioButton();
        ra54 = new javax.swing.JRadioButton();
        ra55 = new javax.swing.JRadioButton();
        ra56 = new javax.swing.JRadioButton();
        ra57 = new javax.swing.JRadioButton();
        lblpregunta14 = new javax.swing.JLabel();
        ra58 = new javax.swing.JRadioButton();
        ra59 = new javax.swing.JRadioButton();
        ra60 = new javax.swing.JRadioButton();
        ra61 = new javax.swing.JRadioButton();
        lblpregunta15 = new javax.swing.JLabel();
        ra62 = new javax.swing.JRadioButton();
        ra63 = new javax.swing.JRadioButton();
        ra64 = new javax.swing.JRadioButton();
        ra65 = new javax.swing.JRadioButton();
        lblpregunta16 = new javax.swing.JLabel();
        ra66 = new javax.swing.JRadioButton();
        ra67 = new javax.swing.JRadioButton();
        ra68 = new javax.swing.JRadioButton();
        ra69 = new javax.swing.JRadioButton();
        lblpregunta17 = new javax.swing.JLabel();
        ra70 = new javax.swing.JRadioButton();
        ra71 = new javax.swing.JRadioButton();
        ra72 = new javax.swing.JRadioButton();
        lblpregunta18 = new javax.swing.JLabel();
        ra73 = new javax.swing.JRadioButton();
        ra74 = new javax.swing.JRadioButton();
        ra75 = new javax.swing.JRadioButton();
        lblpregunta19 = new javax.swing.JLabel();
        ra76 = new javax.swing.JRadioButton();
        ra77 = new javax.swing.JRadioButton();
        ra78 = new javax.swing.JRadioButton();
        lblpregunta20 = new javax.swing.JLabel();
        ra79 = new javax.swing.JRadioButton();
        ra80 = new javax.swing.JRadioButton();
        ra81 = new javax.swing.JRadioButton();
        btnguardar = new javax.swing.JButton();
        lblmensaje2 = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();
        lblimagen2 = new javax.swing.JLabel();
        lblimagen3 = new javax.swing.JLabel();
        lblpregunta1 = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtNumeroId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jScrollPane1.setDoubleBuffered(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(120, 120));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(120, 120));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 5000));
        jScrollPane1.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 56000));
        jPanel1.setLayout(null);

        lblmensaje1.setForeground(new java.awt.Color(0, 51, 204));
        lblmensaje1.setText("<html>Desarrolle cada una de las preguntas con única respuesta.</html>");
        jPanel1.add(lblmensaje1);
        lblmensaje1.setBounds(16, 58, 290, 30);

        pre1.add(ra1);
        ra1.setText("a) Horno");
        ra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra1ActionPerformed(evt);
            }
        });
        jPanel1.add(ra1);
        ra1.setBounds(10, 150, 67, 23);

        pre1.add(ra2);
        ra2.setText("b) Extintor");
        ra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra2ActionPerformed(evt);
            }
        });
        jPanel1.add(ra2);
        ra2.setBounds(10, 170, 77, 23);

        pre1.add(ra3);
        ra3.setText("c) Fuego");
        ra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra3ActionPerformed(evt);
            }
        });
        jPanel1.add(ra3);
        ra3.setBounds(10, 190, 67, 23);

        pre1.add(ra4);
        ra4.setText("d) Gato");
        ra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra4ActionPerformed(evt);
            }
        });
        jPanel1.add(ra4);
        ra4.setBounds(10, 210, 61, 23);

        pre1.add(ra5);
        ra5.setText("e) Techo");
        ra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra5ActionPerformed(evt);
            }
        });
        jPanel1.add(ra5);
        ra5.setBounds(10, 240, 67, 23);

        lblpregunta2.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta2.setText("2.   ¿Cuál es el animal que NO debería estar aquí?");
        jPanel1.add(lblpregunta2);
        lblpregunta2.setBounds(10, 264, 237, 14);

        pre2.add(ra6);
        ra6.setText("a) Cerdo");
        ra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra6ActionPerformed(evt);
            }
        });
        jPanel1.add(ra6);
        ra6.setBounds(10, 285, 67, 23);

        pre2.add(ra7);
        ra7.setText("b) Cabra");
        ra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra7ActionPerformed(evt);
            }
        });
        jPanel1.add(ra7);
        ra7.setBounds(10, 308, 67, 23);

        pre2.add(ra8);
        ra8.setText("c) Oveja");
        ra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra8ActionPerformed(evt);
            }
        });
        jPanel1.add(ra8);
        ra8.setBounds(10, 331, 67, 23);

        pre2.add(ra9);
        ra9.setText("d) Oso");
        ra9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra9ActionPerformed(evt);
            }
        });
        jPanel1.add(ra9);
        ra9.setBounds(10, 354, 57, 23);

        pre2.add(ra10);
        ra10.setText("e) Gallina");
        ra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra10ActionPerformed(evt);
            }
        });
        jPanel1.add(ra10);
        ra10.setBounds(10, 377, 69, 23);

        pre2.add(ra11);
        ra11.setText("f) Vaca ");
        ra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra11ActionPerformed(evt);
            }
        });
        jPanel1.add(ra11);
        ra11.setBounds(10, 400, 63, 23);

        lblpregunta3.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta3.setText("3.    ¿Cuál es la ficha que sigue en la siguiente serie?          ");
        jPanel1.add(lblpregunta3);
        lblpregunta3.setBounds(10, 441, 281, 14);

        pre3.add(ra12);
        ra12.setText("a) La ficha (a) es la que sigue la serie");
        ra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra12ActionPerformed(evt);
            }
        });
        jPanel1.add(ra12);
        ra12.setBounds(6, 652, 203, 23);

        pre3.add(ra13);
        ra13.setText("b) La ficha( b) es la que sigue la serie");
        ra13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra13ActionPerformed(evt);
            }
        });
        jPanel1.add(ra13);
        ra13.setBounds(6, 678, 203, 23);

        pre3.add(ra14);
        ra14.setText("c) La ficha (c) es la que sigue la serie");
        ra14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra14ActionPerformed(evt);
            }
        });
        jPanel1.add(ra14);
        ra14.setBounds(6, 701, 201, 23);

        pre3.add(ra15);
        ra15.setText("d) La ficha (d) es la que sigue la serie");
        ra15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra15ActionPerformed(evt);
            }
        });
        jPanel1.add(ra15);
        ra15.setBounds(6, 727, 203, 23);

        lblpregunta4.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta4.setText("<html>4. ¿Cuál es valor que sigue en esta serie?  4   -   6   -   8   -   10   -   ? </html>                 ");
        jPanel1.add(lblpregunta4);
        lblpregunta4.setBounds(10, 768, 206, 36);

        pre4.add(ra16);
        ra16.setText("a)  9");
        ra16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra16ActionPerformed(evt);
            }
        });
        jPanel1.add(ra16);
        ra16.setBounds(10, 806, 47, 23);

        pre4.add(ra17);
        ra17.setText("b) 11");
        ra17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra17ActionPerformed(evt);
            }
        });
        jPanel1.add(ra17);
        ra17.setBounds(10, 829, 51, 23);

        pre4.add(ra18);
        ra18.setText("c) 12");
        ra18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra18ActionPerformed(evt);
            }
        });
        jPanel1.add(ra18);
        ra18.setBounds(10, 852, 49, 23);

        pre4.add(ra19);
        ra19.setText("d) 14");
        ra19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra19ActionPerformed(evt);
            }
        });
        jPanel1.add(ra19);
        ra19.setBounds(10, 875, 51, 23);

        lblpregunta5.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta5.setText("<html>5. ¿Cuál es la palabra que completa la siguiente frase? León es a carnívoro como ciervo es a __________ </html>");
        jPanel1.add(lblpregunta5);
        lblpregunta5.setBounds(10, 900, 281, 40);

        pre5.add(ra20);
        ra20.setText("a) Mamífero");
        ra20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra20ActionPerformed(evt);
            }
        });
        jPanel1.add(ra20);
        ra20.setBounds(10, 942, 83, 23);

        pre5.add(ra21);
        ra21.setText("b) Macho");
        ra21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra21ActionPerformed(evt);
            }
        });
        jPanel1.add(ra21);
        ra21.setBounds(10, 965, 69, 23);

        pre5.add(ra22);
        ra22.setText("c) Hervívoro");
        ra22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra22ActionPerformed(evt);
            }
        });
        jPanel1.add(ra22);
        ra22.setBounds(10, 988, 85, 23);

        pre5.add(ra23);
        ra23.setText("d) Animal");
        ra23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra23ActionPerformed(evt);
            }
        });
        jPanel1.add(ra23);
        ra23.setBounds(10, 1011, 69, 23);

        lblpregunta6.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta6.setText("6) ¿Qué palabra está mal escrita ortográficamente?");
        jPanel1.add(lblpregunta6);
        lblpregunta6.setBounds(10, 1052, 246, 14);

        pre6.add(ra24);
        ra24.setText("a) Abuelo");
        ra24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra24ActionPerformed(evt);
            }
        });
        jPanel1.add(ra24);
        ra24.setBounds(10, 1073, 71, 23);

        pre6.add(ra25);
        ra25.setText("b) Oveja");
        ra25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra25ActionPerformed(evt);
            }
        });
        jPanel1.add(ra25);
        ra25.setBounds(10, 1096, 67, 23);

        pre6.add(ra26);
        ra26.setText("c) biajar");
        ra26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra26ActionPerformed(evt);
            }
        });
        jPanel1.add(ra26);
        ra26.setBounds(10, 1119, 65, 23);

        pre6.add(ra27);
        ra27.setText("d) Alcohol");
        ra27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra27ActionPerformed(evt);
            }
        });
        jPanel1.add(ra27);
        ra27.setBounds(10, 1142, 73, 23);

        lblpregunta7.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta7.setText("7)  ¿Cuantos círculos hay en este dibujo?");
        jPanel1.add(lblpregunta7);
        lblpregunta7.setBounds(10, 1417, 196, 14);

        pre7.add(ra28);
        ra28.setText("a) 9");
        ra28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra28ActionPerformed(evt);
            }
        });
        jPanel1.add(ra28);
        ra28.setBounds(10, 1438, 45, 23);

        pre7.add(ra29);
        ra29.setText("b) 10");
        ra29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra29ActionPerformed(evt);
            }
        });
        jPanel1.add(ra29);
        ra29.setBounds(10, 1464, 51, 23);

        pre7.add(ra30);
        ra30.setText("c) 8");
        ra30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra30ActionPerformed(evt);
            }
        });
        jPanel1.add(ra30);
        ra30.setBounds(10, 1487, 43, 23);

        pre7.add(ra31);
        ra31.setText("d) 7");
        ra31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra31ActionPerformed(evt);
            }
        });
        jPanel1.add(ra31);
        ra31.setBounds(10, 1513, 45, 23);

        lblpregunta8.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta8.setText("<html>8. ¿Cuál es valor que sigue en esta serie? 1   -   1   -   2   -   3   -   5   -   8   -   ?</html>");
        jPanel1.add(lblpregunta8);
        lblpregunta8.setBounds(10, 1538, 214, 33);

        pre8.add(ra32);
        ra32.setText("a) 13");
        ra32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra32ActionPerformed(evt);
            }
        });
        jPanel1.add(ra32);
        ra32.setBounds(10, 1573, 51, 18);

        pre8.add(ra33);
        ra33.setText("b) 12");
        ra33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra33ActionPerformed(evt);
            }
        });
        jPanel1.add(ra33);
        ra33.setBounds(10, 1591, 51, 23);

        pre8.add(ra34);
        ra34.setText("c) 15 ");
        ra34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra34ActionPerformed(evt);
            }
        });
        jPanel1.add(ra34);
        ra34.setBounds(10, 1614, 53, 23);

        pre8.add(ra35);
        ra35.setText("d) 11");
        ra35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra35ActionPerformed(evt);
            }
        });
        jPanel1.add(ra35);
        ra35.setBounds(10, 1637, 51, 23);

        lblpregunta9.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta9.setText("9. ¿Qué palabra no es sinónima a las demás?");
        jPanel1.add(lblpregunta9);
        lblpregunta9.setBounds(10, 1667, 214, 14);

        pre9.add(ra36);
        ra36.setText("a) Burro");
        ra36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra36ActionPerformed(evt);
            }
        });
        jPanel1.add(ra36);
        ra36.setBounds(10, 1691, 65, 23);

        pre9.add(ra37);
        ra37.setText("b) Asno");
        ra37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra37ActionPerformed(evt);
            }
        });
        jPanel1.add(ra37);
        ra37.setBounds(10, 1714, 63, 23);

        pre9.add(ra38);
        ra38.setText("c) Pollino");
        ra38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra38ActionPerformed(evt);
            }
        });
        jPanel1.add(ra38);
        ra38.setBounds(10, 1737, 67, 23);

        pre9.add(ra39);
        ra39.setText("d) Mulo");
        ra39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra39ActionPerformed(evt);
            }
        });
        jPanel1.add(ra39);
        ra39.setBounds(10, 1760, 61, 23);

        pre9.add(ra40);
        ra40.setText("e) Jumento");
        ra40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra40ActionPerformed(evt);
            }
        });
        jPanel1.add(ra40);
        ra40.setBounds(10, 1783, 79, 23);

        lblpregunta10.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta10.setText("10.¿Las gallinas vuelan?");
        jPanel1.add(lblpregunta10);
        lblpregunta10.setBounds(10, 1813, 115, 14);

        pre10.add(ra41);
        ra41.setText("a) Sí, pueden volar");
        ra41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra41ActionPerformed(evt);
            }
        });
        jPanel1.add(ra41);
        ra41.setBounds(10, 1834, 117, 23);

        pre10.add(ra42);
        ra42.setText("b) No, no pueden volar");
        ra42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra42ActionPerformed(evt);
            }
        });
        jPanel1.add(ra42);
        ra42.setBounds(10, 1857, 137, 23);

        pre10.add(ra43);
        ra43.setText("c) Algunas pueden volar y otras no");
        ra43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra43ActionPerformed(evt);
            }
        });
        jPanel1.add(ra43);
        ra43.setBounds(10, 1880, 193, 23);

        pre10.add(ra44);
        ra44.setText("d) Solo vuelan los gallos.");
        ra44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra44ActionPerformed(evt);
            }
        });
        jPanel1.add(ra44);
        ra44.setBounds(10, 1903, 143, 23);

        lblpregunta11.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta11.setText("<html>11. ¿Cuál es el resultado de la siguiente operación? ( 6 x 5 ) : 3 =</html>         ");
        jPanel1.add(lblpregunta11);
        lblpregunta11.setBounds(10, 1933, 249, 31);

        ra45.setText("a) 33");
        ra45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra45ActionPerformed(evt);
            }
        });
        jPanel1.add(ra45);
        ra45.setBounds(10, 1971, 51, 23);

        ra46.setText("b) 1");
        ra46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra46ActionPerformed(evt);
            }
        });
        jPanel1.add(ra46);
        ra46.setBounds(10, 1994, 45, 23);

        ra47.setText("c) 10");
        ra47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra47ActionPerformed(evt);
            }
        });
        jPanel1.add(ra47);
        ra47.setBounds(10, 2017, 49, 23);

        pre11.add(ra48);
        ra48.setText("d) 30");
        ra48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra48ActionPerformed(evt);
            }
        });
        jPanel1.add(ra48);
        ra48.setBounds(10, 2040, 51, 23);

        lblpregunta12.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta12.setText("12.  SACO es a ASCO como 7683 es a:");
        jPanel1.add(lblpregunta12);
        lblpregunta12.setBounds(10, 2073, 186, 14);

        pre12.add(ra49);
        ra49.setText("a)  8376");
        ra49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra49ActionPerformed(evt);
            }
        });
        jPanel1.add(ra49);
        ra49.setBounds(10, 2094, 65, 23);

        pre12.add(ra50);
        ra50.setText("b)  6783");
        ra50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra50ActionPerformed(evt);
            }
        });
        jPanel1.add(ra50);
        ra50.setBounds(10, 2117, 65, 23);

        pre12.add(ra51);
        ra51.setText("c)   3867");
        ra51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra51ActionPerformed(evt);
            }
        });
        jPanel1.add(ra51);
        ra51.setBounds(10, 2140, 67, 23);

        pre12.add(ra52);
        ra52.setText("d)  3678");
        ra52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra52ActionPerformed(evt);
            }
        });
        jPanel1.add(ra52);
        ra52.setBounds(10, 2163, 65, 23);

        lblpregunta13.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta13.setText("13. ¿Qué palabra no se corresponde con el resto?");
        jPanel1.add(lblpregunta13);
        lblpregunta13.setBounds(10, 2196, 239, 14);

        pre13.add(ra53);
        ra53.setText("a) Collar");
        ra53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra53ActionPerformed(evt);
            }
        });
        jPanel1.add(ra53);
        ra53.setBounds(10, 2228, 65, 23);

        pre13.add(ra54);
        ra54.setText("b) Abdomen");
        ra54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra54ActionPerformed(evt);
            }
        });
        jPanel1.add(ra54);
        ra54.setBounds(10, 2251, 83, 23);

        pre13.add(ra55);
        ra55.setText("c) Pierna");
        ra55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra55ActionPerformed(evt);
            }
        });
        jPanel1.add(ra55);
        ra55.setBounds(10, 2274, 67, 23);

        pre13.add(ra56);
        ra56.setText("d) Brazo");
        ra56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra56ActionPerformed(evt);
            }
        });
        jPanel1.add(ra56);
        ra56.setBounds(10, 2297, 65, 23);

        pre13.add(ra57);
        ra57.setText("e) Mano");
        ra57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra57ActionPerformed(evt);
            }
        });
        jPanel1.add(ra57);
        ra57.setBounds(10, 2320, 65, 23);

        lblpregunta14.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta14.setText("14. . ¿Cuál es la palabra que completa la siguiente frase? En otoño las ______ de muchos árboles caen ");
        jPanel1.add(lblpregunta14);
        lblpregunta14.setBounds(10, 2361, 495, 14);

        pre14.add(ra58);
        ra58.setText("a) Ramas");
        ra58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra58ActionPerformed(evt);
            }
        });
        jPanel1.add(ra58);
        ra58.setBounds(10, 2393, 71, 23);

        pre14.add(ra59);
        ra59.setText("b) Flores");
        ra59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra59ActionPerformed(evt);
            }
        });
        jPanel1.add(ra59);
        ra59.setBounds(10, 2416, 67, 23);

        pre14.add(ra60);
        ra60.setText("c) Frutas");
        ra60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra60ActionPerformed(evt);
            }
        });
        jPanel1.add(ra60);
        ra60.setBounds(10, 2439, 69, 23);

        pre14.add(ra61);
        ra61.setText("d) Hojas");
        ra61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra61ActionPerformed(evt);
            }
        });
        jPanel1.add(ra61);
        ra61.setBounds(10, 2462, 65, 23);

        lblpregunta15.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta15.setText("<html>15. Hoy he ido a comprar naranjas, la dependienta me ha dado 6, yo me he comido 1 y mi padre 2, otra se ha caído y se ha estropeado. ¿Cuántas naranjas me quedan?</hmtl>");
        jPanel1.add(lblpregunta15);
        lblpregunta15.setBounds(10, 2503, 413, 45);

        pre15.add(ra62);
        ra62.setText("a) 2");
        ra62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra62ActionPerformed(evt);
            }
        });
        jPanel1.add(ra62);
        ra62.setBounds(10, 2566, 45, 23);

        pre15.add(ra63);
        ra63.setText("b) 5");
        ra63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra63ActionPerformed(evt);
            }
        });
        jPanel1.add(ra63);
        ra63.setBounds(10, 2589, 45, 23);

        pre15.add(ra64);
        ra64.setText("c) 4");
        ra64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra64ActionPerformed(evt);
            }
        });
        jPanel1.add(ra64);
        ra64.setBounds(10, 2612, 43, 23);

        pre15.add(ra65);
        ra65.setText("d) Ninguna");
        ra65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra65ActionPerformed(evt);
            }
        });
        jPanel1.add(ra65);
        ra65.setBounds(10, 2635, 77, 23);

        lblpregunta16.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta16.setText("16. . Señala qué reloj de los que aparece más abajo completa correctamente la siguiente serie:");
        jPanel1.add(lblpregunta16);
        lblpregunta16.setBounds(10, 2676, 455, 14);

        pre16.add(ra66);
        ra66.setText("a) El reloj a) es el que sigue la serie");
        ra66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra66ActionPerformed(evt);
            }
        });
        jPanel1.add(ra66);
        ra66.setBounds(10, 2972, 195, 23);

        pre16.add(ra67);
        ra67.setText("b) El reloj b) es el que sigue la serie");
        ra67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra67ActionPerformed(evt);
            }
        });
        jPanel1.add(ra67);
        ra67.setBounds(10, 2995, 195, 23);

        pre16.add(ra68);
        ra68.setText("c) El reloj c) es el que sigue la serie");
        ra68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra68ActionPerformed(evt);
            }
        });
        jPanel1.add(ra68);
        ra68.setBounds(10, 3018, 193, 23);

        pre16.add(ra69);
        ra69.setText("d) El reloj d) es el que sigue la serie");
        ra69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra69ActionPerformed(evt);
            }
        });
        jPanel1.add(ra69);
        ra69.setBounds(10, 3041, 195, 23);

        lblpregunta17.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta17.setText("17. Tú prefieres:");
        jPanel1.add(lblpregunta17);
        lblpregunta17.setBounds(10, 3082, 81, 14);

        pre17.add(ra70);
        ra70.setText("a) Escuchar alguna noticia");
        ra70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra70ActionPerformed(evt);
            }
        });
        jPanel1.add(ra70);
        ra70.setBounds(6, 3114, 151, 23);

        pre17.add(ra71);
        ra71.setText("b) Escribir alguna noticia");
        ra71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra71ActionPerformed(evt);
            }
        });
        jPanel1.add(ra71);
        ra71.setBounds(6, 3137, 141, 23);

        pre17.add(ra72);
        ra72.setText("c) Ver alguan noticia");
        ra72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra72ActionPerformed(evt);
            }
        });
        jPanel1.add(ra72);
        ra72.setBounds(6, 3160, 123, 23);

        lblpregunta18.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta18.setText("18.  En tus próximas vacaciones, ¿qué  harías? ");
        jPanel1.add(lblpregunta18);
        lblpregunta18.setBounds(10, 3190, 498, 24);

        pre18.add(ra73);
        ra73.setText("a) Observar el paisaje");
        ra73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra73ActionPerformed(evt);
            }
        });
        jPanel1.add(ra73);
        ra73.setBounds(10, 3216, 131, 23);

        pre18.add(ra74);
        ra74.setText("b) Sentir el viento");
        ra74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra74ActionPerformed(evt);
            }
        });
        jPanel1.add(ra74);
        ra74.setBounds(10, 3242, 111, 23);

        pre18.add(ra75);
        ra75.setText("c) Escuchar los sonidos naturales");
        ra75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra75ActionPerformed(evt);
            }
        });
        jPanel1.add(ra75);
        ra75.setBounds(10, 3268, 183, 23);

        lblpregunta19.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta19.setText("19.  Para aprender necesitas:   ");
        jPanel1.add(lblpregunta19);
        lblpregunta19.setBounds(10, 3309, 152, 14);

        pre19.add(ra76);
        ra76.setText("a) Leer un libro");
        ra76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra76ActionPerformed(evt);
            }
        });
        jPanel1.add(ra76);
        ra76.setBounds(10, 3341, 97, 23);

        pre19.add(ra77);
        ra77.setText("b) Escuchar una clase");
        ra77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra77ActionPerformed(evt);
            }
        });
        jPanel1.add(ra77);
        ra77.setBounds(10, 3364, 129, 23);

        pre19.add(ra78);
        ra78.setText("c) participar en clase");
        ra78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra78ActionPerformed(evt);
            }
        });
        jPanel1.add(ra78);
        ra78.setBounds(10, 3387, 125, 23);

        lblpregunta20.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta20.setText("20.  En una mascota que te gusta más: ");
        jPanel1.add(lblpregunta20);
        lblpregunta20.setBounds(10, 3428, 191, 14);

        pre20.add(ra79);
        ra79.setText("a) oír sus ladridos");
        ra79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra79ActionPerformed(evt);
            }
        });
        jPanel1.add(ra79);
        ra79.setBounds(6, 3460, 109, 23);

        pre20.add(ra80);
        ra80.setText("b) acariciar su pelaje");
        ra80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra80ActionPerformed(evt);
            }
        });
        jPanel1.add(ra80);
        ra80.setBounds(6, 3483, 125, 23);

        pre20.add(ra81);
        ra81.setText("c) V er sus juegos");
        ra81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra81ActionPerformed(evt);
            }
        });
        jPanel1.add(ra81);
        ra81.setBounds(6, 3506, 111, 23);

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 255));
        btnguardar.setText("GUARDAR TEST DE INTELIGENCIA");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar);
        btnguardar.setBounds(330, 3620, 240, 23);

        lblmensaje2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        lblmensaje2.setText("<HTML>Gracias Por  la atención prestada durante este TEST");
        jPanel1.add(lblmensaje2);
        lblmensaje2.setBounds(40, 3570, 280, 110);

        lblimagen1.setIcon(new javax.swing.ImageIcon("E:\\1.png")); // NOI18N
        jPanel1.add(lblimagen1);
        lblimagen1.setBounds(106, 473, 227, 146);

        lblimagen2.setIcon(new javax.swing.ImageIcon("E:\\2.png")); // NOI18N
        lblimagen2.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel1.add(lblimagen2);
        lblimagen2.setBounds(79, 1167, 284, 244);

        lblimagen3.setIcon(new javax.swing.ImageIcon("E:\\3.jpg")); // NOI18N
        jPanel1.add(lblimagen3);
        lblimagen3.setBounds(40, 2708, 454, 246);

        lblpregunta1.setForeground(new java.awt.Color(0, 51, 204));
        lblpregunta1.setText("<html>1.  ¿Cuál es la palabra que completa la siguiente frase? Los bomberos apagaron el _________ que había en la casa y pudieron salvar a las personas que vivían dentro </html>");
        jPanel1.add(lblpregunta1);
        lblpregunta1.setBounds(10, 100, 464, 40);

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitulo.setText("TEST DE INTELIGENCIA MÚLTIPLES");
        jPanel1.add(lbltitulo);
        lbltitulo.setBounds(189, 10, 240, 15);

        lblid.setForeground(new java.awt.Color(0, 51, 204));
        lblid.setText("Numero de Identificacion");
        jPanel1.add(lblid);
        lblid.setBounds(189, 30, 140, 14);

        lblnombres.setForeground(new java.awt.Color(0, 51, 204));
        lblnombres.setText("Nombre");
        jPanel1.add(lblnombres);
        lblnombres.setBounds(10, 35, 37, 14);
        jPanel1.add(txtnombres);
        txtnombres.setBounds(50, 30, 110, 20);

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar);
        btnbuscar.setBounds(490, 30, 73, 23);
        jPanel1.add(txtNumeroId);
        txtNumeroId.setBounds(340, 30, 110, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Desktop\\cerebros-creativos.jpg")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 1000));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, -210, 1000, 1190);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 819, 3770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:

        try
        {
            String criterio=txtNumeroId.getText();
            conexionBD conexion=new conexionBD();
            Statement sentencia=conexion.getconexion().createStatement();
            ResultSet resultado=sentencia.executeQuery("Select * from Registro where(Numero_Identificacion='"+criterio+"')");

            while(resultado.next())
            {

                txtNumeroId.setText(""+resultado.getString("Numero_Identificacion"));
                txtnombres.setText(""+resultado.getString("Nombres"));

            }
            resultado.close();
            conexion.getconexion().close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error :"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
            this.contarRespuetas();
               
                try
            {
                conexionBD conexion=new conexionBD();
                String Nombres=txtnombres.getText();
                String Numero_Identificacion=txtNumeroId.getText();

                String instruccion="Insert into Test (Numero_Identificacion,Nombres,pregunta1,pregunta2,pregunta3,pregunta4,pregunta5,pregunta6,pregunta7,pregunta8,pregunta9,pregunta10,pregunta11,pregunta12,pregunta13,pregunta14,pregunta15,pregunta16,pregunta17,pregunta18,pregunta19,pregunta20,Tipo_Inteligencia,Tipo_Aprendizaje)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                conexion.sentencia=conexion.getconexion().prepareStatement(instruccion);
                conexion.sentencia.setString(1, Numero_Identificacion);
                conexion.sentencia.setString(2, Nombres);
                conexion.sentencia.setString(3, pregunta1.getRespuesta());
                conexion.sentencia.setString(4, pregunta2.getRespuesta());
                conexion.sentencia.setString(5, pregunta3.getRespuesta());
                conexion.sentencia.setString(6, pregunta4.getRespuesta());
                conexion.sentencia.setString(7, pregunta5.getRespuesta());
                conexion.sentencia.setString(8, pregunta6.getRespuesta());
                conexion.sentencia.setString(9, pregunta7.getRespuesta());
                conexion.sentencia.setString(10, pregunta8.getRespuesta());
                conexion.sentencia.setString(11, pregunta9.getRespuesta());
                conexion.sentencia.setString(12, pregunta10.getRespuesta());
                conexion.sentencia.setString(13, pregunta11.getRespuesta());
                conexion.sentencia.setString(14, pregunta12.getRespuesta());
                conexion.sentencia.setString(15, pregunta13.getRespuesta());
                conexion.sentencia.setString(16, pregunta14.getRespuesta());
                conexion.sentencia.setString(17, pregunta15.getRespuesta());
                conexion.sentencia.setString(18, pregunta16.getRespuesta());
                conexion.sentencia.setString(19, pregunta17);
                conexion.sentencia.setString(20, pregunta18);
                conexion.sentencia.setString(21, pregunta19);
                conexion.sentencia.setString(22, pregunta20);               
                
                if(respuetasLinguistica>respuetasMatematicas){
                    conexion.sentencia.setString(23, "Inteligencia Linguisticas");
                   
                 dispose();
                    
                }        
                else{
                    conexion.sentencia.setString(23,"Inteligencia Matematica");
                  
                 dispose();
                    
                }
               
                 if(pregunta17=="A" && pregunta18=="C" && pregunta19=="B" && pregunta20=="A"){
                    
                    conexion.sentencia.setString(24,Taprendizaje1);
                    JOptionPane.showMessageDialog(this,"Tipo de Aprendizaje: "+Taprendizaje1,"Informacion",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    if(pregunta17=="C" && pregunta18=="A" && pregunta19=="A" && pregunta20=="C"){
                       conexion.sentencia.setString(24,Taprendizaje2);
                    JOptionPane.showMessageDialog(this,"Tipo de Aprendizaje: "+Taprendizaje2,"Informacion",JOptionPane.INFORMATION_MESSAGE); 
                        
                    }
                    else{
                        
                        conexion.sentencia.setString(24,Taprendizaje3);
                    JOptionPane.showMessageDialog(this,"Tipo de Aprendizaje: "+Taprendizaje3,"Informacion",JOptionPane.INFORMATION_MESSAGE);
                        
                    }
                }
                    
        
                conexion.sentencia.execute();
                        JOptionPane.showMessageDialog(this,"Test Guardado","Informacion",JOptionPane.INFORMATION_MESSAGE);
                        conexion.getconexion().close();
                        
                
                
                String linguisticas = String.valueOf(this.respuetasLinguistica);
                String matematicas = String.valueOf(this.respuetasMatematicas);
                JOptionPane.showMessageDialog(this,"Linguisticas:" + linguisticas + " " 
                        + "Matematicas:" +matematicas , "Respuestas",JOptionPane.INFORMATION_MESSAGE);
                 
                 if(respuetasLinguistica>respuetasMatematicas){
                     
                    di.setVisible(true);  
                 }
                else{
                     di1.setVisible(true);
                 }
                        
            }
                
          catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this,"Error SQL"+e,"Informacion",JOptionPane.ERROR_MESSAGE);
            }
            
                              
                
           


    }//GEN-LAST:event_btnguardarActionPerformed

    private void ra81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra81ActionPerformed
        // TODO add your handling code here:
        pregunta20=("C");
    }//GEN-LAST:event_ra81ActionPerformed

    private void ra80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra80ActionPerformed
        // TODO add your handling code here:
        pregunta20=("B");
    }//GEN-LAST:event_ra80ActionPerformed

    private void ra79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra79ActionPerformed
        // TODO add your handling code here:
        pregunta20=("A");
    }//GEN-LAST:event_ra79ActionPerformed

    private void ra78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra78ActionPerformed
        // TODO add your handling code here:
        pregunta19=("C");
    }//GEN-LAST:event_ra78ActionPerformed

    private void ra77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra77ActionPerformed
        // TODO add your handling code here:
        pregunta19=("B");
    }//GEN-LAST:event_ra77ActionPerformed

    private void ra76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra76ActionPerformed
        // TODO add your handling code here:
        pregunta19=("A");
    }//GEN-LAST:event_ra76ActionPerformed

    private void ra75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra75ActionPerformed
        // TODO add your handling code here:
        pregunta18=("C");
    }//GEN-LAST:event_ra75ActionPerformed

    private void ra74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra74ActionPerformed
        // TODO add your handling code here:
        pregunta18=("B");
    }//GEN-LAST:event_ra74ActionPerformed

    private void ra73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra73ActionPerformed
        // TODO add your handling code here:
        pregunta18=("A");
    }//GEN-LAST:event_ra73ActionPerformed

    private void ra72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra72ActionPerformed
        // TODO add your handling code here:
        pregunta17=("C");
    }//GEN-LAST:event_ra72ActionPerformed

    private void ra71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra71ActionPerformed
        // TODO add your handling code here:
        pregunta17=("B");
    }//GEN-LAST:event_ra71ActionPerformed

    private void ra70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra70ActionPerformed
        // TODO add your handling code here:
        pregunta17=("A");
    }//GEN-LAST:event_ra70ActionPerformed

    private void ra69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra69ActionPerformed
        // TODO add your handling code here:
        pregunta16.setValorInsertado("D");
    }//GEN-LAST:event_ra69ActionPerformed

    private void ra68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra68ActionPerformed
        // TODO add your handling code here:
        pregunta16.setValorInsertado("C");
    }//GEN-LAST:event_ra68ActionPerformed

    private void ra67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra67ActionPerformed
        // TODO add your handling code here:
        pregunta16.setValorInsertado("B");
    }//GEN-LAST:event_ra67ActionPerformed

    private void ra66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra66ActionPerformed
        // TODO add your handling code here:
        pregunta16.setValorInsertado("A");
    }//GEN-LAST:event_ra66ActionPerformed

    private void ra65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra65ActionPerformed
        // TODO add your handling code here:
        pregunta15.setValorInsertado("D");
    }//GEN-LAST:event_ra65ActionPerformed

    private void ra64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra64ActionPerformed
        // TODO add your handling code here:
        pregunta15.setValorInsertado("C");
    }//GEN-LAST:event_ra64ActionPerformed

    private void ra63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra63ActionPerformed
        // TODO add your handling code here:
        pregunta15.setValorInsertado("B");
    }//GEN-LAST:event_ra63ActionPerformed

    private void ra62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra62ActionPerformed
        // TODO add your handling code here:
        pregunta15.setValorInsertado("A");
    }//GEN-LAST:event_ra62ActionPerformed

    private void ra61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra61ActionPerformed
        // TODO add your handling code here:
        pregunta14.setValorInsertado("D");
    }//GEN-LAST:event_ra61ActionPerformed

    private void ra60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra60ActionPerformed
        // TODO add your handling code here:
        pregunta14.setValorInsertado("C");
    }//GEN-LAST:event_ra60ActionPerformed

    private void ra59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra59ActionPerformed
        // TODO add your handling code here:
        pregunta14.setValorInsertado("B");
    }//GEN-LAST:event_ra59ActionPerformed

    private void ra58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra58ActionPerformed
        // TODO add your handling code here:
        pregunta14.setValorInsertado("A");
    }//GEN-LAST:event_ra58ActionPerformed

    private void ra57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra57ActionPerformed
        // TODO add your handling code here:
        pregunta13.setValorInsertado("E");
    }//GEN-LAST:event_ra57ActionPerformed

    private void ra56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra56ActionPerformed
        // TODO add your handling code here:
        pregunta13.setValorInsertado("D");
    }//GEN-LAST:event_ra56ActionPerformed

    private void ra55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra55ActionPerformed
        // TODO add your handling code here:
        pregunta13.setValorInsertado("C");
    }//GEN-LAST:event_ra55ActionPerformed

    private void ra54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra54ActionPerformed
        // TODO add your handling code here:
        pregunta13.setValorInsertado("B");
    }//GEN-LAST:event_ra54ActionPerformed

    private void ra53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra53ActionPerformed
        // TODO add your handling code here:
        pregunta13.setValorInsertado("A");
    }//GEN-LAST:event_ra53ActionPerformed

    private void ra52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra52ActionPerformed
        // TODO add your handling code here:
        pregunta12.setValorInsertado("D");
    }//GEN-LAST:event_ra52ActionPerformed

    private void ra51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra51ActionPerformed
        // TODO add your handling code here:
        pregunta12.setValorInsertado("C");
    }//GEN-LAST:event_ra51ActionPerformed

    private void ra50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra50ActionPerformed
        // TODO add your handling code here:
        pregunta12.setValorInsertado("B");
    }//GEN-LAST:event_ra50ActionPerformed

    private void ra49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra49ActionPerformed
        // TODO add your handling code here:
        pregunta12.setValorInsertado("A");
    }//GEN-LAST:event_ra49ActionPerformed

    private void ra48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra48ActionPerformed
        // TODO add your handling code here:
        pregunta11.setValorInsertado("D");
    }//GEN-LAST:event_ra48ActionPerformed

    private void ra47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra47ActionPerformed
        // TODO add your handling code here:
        pregunta11.setValorInsertado("C");
    }//GEN-LAST:event_ra47ActionPerformed

    private void ra46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra46ActionPerformed
        // TODO add your handling code here:
        pregunta11.setValorInsertado("B");
    }//GEN-LAST:event_ra46ActionPerformed

    private void ra45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra45ActionPerformed
        // TODO add your handling code here:
        pregunta11.setValorInsertado("A");
    }//GEN-LAST:event_ra45ActionPerformed

    private void ra44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra44ActionPerformed
        // TODO add your handling code here:
        pregunta10.setValorInsertado("D");
    }//GEN-LAST:event_ra44ActionPerformed

    private void ra43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra43ActionPerformed
        // TODO add your handling code here:
        pregunta10.setValorInsertado("C");
    }//GEN-LAST:event_ra43ActionPerformed

    private void ra42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra42ActionPerformed
        // TODO add your handling code here:
        pregunta10.setValorInsertado("B");
    }//GEN-LAST:event_ra42ActionPerformed

    private void ra41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra41ActionPerformed
        // TODO add your handling code here:
        pregunta10.setValorInsertado("A");
    }//GEN-LAST:event_ra41ActionPerformed

    private void ra40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra40ActionPerformed
        // TODO add your handling code here:
        pregunta9.setValorInsertado("E");
    }//GEN-LAST:event_ra40ActionPerformed

    private void ra39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra39ActionPerformed
        // TODO add your handling code here:
        pregunta9.setValorInsertado("D");
    }//GEN-LAST:event_ra39ActionPerformed

    private void ra38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra38ActionPerformed
        // TODO add your handling code here:
        pregunta9.setValorInsertado("C");
    }//GEN-LAST:event_ra38ActionPerformed

    private void ra37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra37ActionPerformed
        // TODO add your handling code here:
        pregunta9.setValorInsertado("B");
    }//GEN-LAST:event_ra37ActionPerformed

    private void ra36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra36ActionPerformed
        // TODO add your handling code here:
        pregunta9.setValorInsertado("A");
    }//GEN-LAST:event_ra36ActionPerformed

    private void ra35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra35ActionPerformed
        // TODO add your handling code here:
        pregunta8.setValorInsertado("D");
    }//GEN-LAST:event_ra35ActionPerformed

    private void ra34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra34ActionPerformed
        // TODO add your handling code here:
        pregunta8.setValorInsertado("C");
    }//GEN-LAST:event_ra34ActionPerformed

    private void ra33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra33ActionPerformed
        // TODO add your handling code here:
        pregunta8.setValorInsertado("B");
    }//GEN-LAST:event_ra33ActionPerformed

    private void ra32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra32ActionPerformed
        // TODO add your handling code here:
        pregunta8.setValorInsertado("A");
    }//GEN-LAST:event_ra32ActionPerformed

    private void ra31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra31ActionPerformed
        // TODO add your handling code here:
        pregunta7.setValorInsertado("D");
    }//GEN-LAST:event_ra31ActionPerformed

    private void ra30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra30ActionPerformed
        // TODO add your handling code here:
        pregunta7.setValorInsertado("C");
    }//GEN-LAST:event_ra30ActionPerformed

    private void ra29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra29ActionPerformed
        // TODO add your handling code here:
        pregunta7.setValorInsertado("B");
    }//GEN-LAST:event_ra29ActionPerformed

    private void ra28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra28ActionPerformed
        // TODO add your handling code here:
        pregunta7.setValorInsertado("A");
    }//GEN-LAST:event_ra28ActionPerformed

    private void ra27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra27ActionPerformed
        // TODO add your handling code here:
        pregunta6.setValorInsertado("D");
    }//GEN-LAST:event_ra27ActionPerformed

    private void ra26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra26ActionPerformed
        // TODO add your handling code here:
        pregunta6.setValorInsertado("C");
    }//GEN-LAST:event_ra26ActionPerformed

    private void ra25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra25ActionPerformed
        // TODO add your handling code here:
        pregunta6.setValorInsertado("B");
    }//GEN-LAST:event_ra25ActionPerformed

    private void ra24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra24ActionPerformed
        // TODO add your handling code here:
        pregunta6.setValorInsertado("A");
    }//GEN-LAST:event_ra24ActionPerformed

    private void ra23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra23ActionPerformed
        // TODO add your handling code here:
        pregunta5.setValorInsertado("D");
    }//GEN-LAST:event_ra23ActionPerformed

    private void ra22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra22ActionPerformed
        // TODO add your handling code here:
        pregunta5.setValorInsertado("C");
    }//GEN-LAST:event_ra22ActionPerformed

    private void ra21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra21ActionPerformed
        // TODO add your handling code here:
        pregunta5.setValorInsertado("B");
    }//GEN-LAST:event_ra21ActionPerformed

    private void ra20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra20ActionPerformed
        // TODO add your handling code here:
        pregunta5.setValorInsertado("A");
    }//GEN-LAST:event_ra20ActionPerformed

    private void ra19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra19ActionPerformed
        // TODO add your handling code here:
        pregunta4.setValorInsertado("D");
    }//GEN-LAST:event_ra19ActionPerformed

    private void ra18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra18ActionPerformed
        // TODO add your handling code here:
        pregunta4.setValorInsertado("C");
    }//GEN-LAST:event_ra18ActionPerformed

    private void ra17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra17ActionPerformed
        // TODO add your handling code here:
        pregunta4.setValorInsertado("B");
    }//GEN-LAST:event_ra17ActionPerformed

    private void ra16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra16ActionPerformed
        // TODO add your handling code here:
        pregunta4.setValorInsertado("A");
    }//GEN-LAST:event_ra16ActionPerformed

    private void ra15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra15ActionPerformed
        // TODO add your handling code here
        pregunta3.setValorInsertado("D");
    }//GEN-LAST:event_ra15ActionPerformed

    private void ra14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra14ActionPerformed
        // TODO add your handling code here:
        pregunta3.setValorInsertado("C");
    }//GEN-LAST:event_ra14ActionPerformed

    private void ra13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra13ActionPerformed
        // TODO add your handling code here:
        pregunta3.setValorInsertado("B");
    }//GEN-LAST:event_ra13ActionPerformed

    private void ra12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra12ActionPerformed
        // TODO add your handling code here:
        pregunta3.setValorInsertado("A");
    }//GEN-LAST:event_ra12ActionPerformed

    private void ra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra11ActionPerformed
        // TODO add your handling code here:
        pregunta2.setValorInsertado("F");
    }//GEN-LAST:event_ra11ActionPerformed

    private void ra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra10ActionPerformed
        // TODO add your handling code here:
        pregunta2.setValorInsertado("E");
    }//GEN-LAST:event_ra10ActionPerformed

    private void ra9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra9ActionPerformed
        // TODO add your handling code here:
        pregunta2.setValorInsertado("D");
    }//GEN-LAST:event_ra9ActionPerformed

    private void ra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra8ActionPerformed
        // TODO add your handling code here:
        pregunta2.setValorInsertado("C");
    }//GEN-LAST:event_ra8ActionPerformed

    private void ra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra7ActionPerformed
        // TODO add your handling code here:
        pregunta2.setValorInsertado("B");
    }//GEN-LAST:event_ra7ActionPerformed

    private void ra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra6ActionPerformed
        // TODO add your handling code here:
        pregunta2.setValorInsertado("A");
    }//GEN-LAST:event_ra6ActionPerformed

    private void ra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra5ActionPerformed
        // TODO add your handling code here:
        pregunta1.setValorInsertado("E");
    }//GEN-LAST:event_ra5ActionPerformed

    private void ra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra4ActionPerformed
        // TODO add your handling code here:
        pregunta1.setValorInsertado("D");
    }//GEN-LAST:event_ra4ActionPerformed

    private void ra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra3ActionPerformed
        // TODO add your handling code here:
        pregunta1.setValorInsertado("C");
    }//GEN-LAST:event_ra3ActionPerformed

    private void ra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra2ActionPerformed
        // TODO add your handling code here:
        pregunta1.setValorInsertado("B");
    }//GEN-LAST:event_ra2ActionPerformed

    private void ra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra1ActionPerformed
        // TODO add your handling code here:
        pregunta1.setValorInsertado("A");
    }//GEN-LAST:event_ra1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    private javax.swing.JLabel lblimagen3;
    private javax.swing.JLabel lblmensaje1;
    private javax.swing.JLabel lblmensaje2;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblpregunta1;
    private javax.swing.JLabel lblpregunta10;
    private javax.swing.JLabel lblpregunta11;
    private javax.swing.JLabel lblpregunta12;
    private javax.swing.JLabel lblpregunta13;
    private javax.swing.JLabel lblpregunta14;
    private javax.swing.JLabel lblpregunta15;
    private javax.swing.JLabel lblpregunta16;
    private javax.swing.JLabel lblpregunta17;
    private javax.swing.JLabel lblpregunta18;
    private javax.swing.JLabel lblpregunta19;
    private javax.swing.JLabel lblpregunta2;
    private javax.swing.JLabel lblpregunta20;
    private javax.swing.JLabel lblpregunta3;
    private javax.swing.JLabel lblpregunta4;
    private javax.swing.JLabel lblpregunta5;
    private javax.swing.JLabel lblpregunta6;
    private javax.swing.JLabel lblpregunta7;
    private javax.swing.JLabel lblpregunta8;
    private javax.swing.JLabel lblpregunta9;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.ButtonGroup pre1;
    private javax.swing.ButtonGroup pre10;
    private javax.swing.ButtonGroup pre11;
    private javax.swing.ButtonGroup pre12;
    private javax.swing.ButtonGroup pre13;
    private javax.swing.ButtonGroup pre14;
    private javax.swing.ButtonGroup pre15;
    private javax.swing.ButtonGroup pre16;
    private javax.swing.ButtonGroup pre17;
    private javax.swing.ButtonGroup pre18;
    private javax.swing.ButtonGroup pre19;
    private javax.swing.ButtonGroup pre2;
    private javax.swing.ButtonGroup pre20;
    private javax.swing.ButtonGroup pre3;
    private javax.swing.ButtonGroup pre4;
    private javax.swing.ButtonGroup pre5;
    private javax.swing.ButtonGroup pre6;
    private javax.swing.ButtonGroup pre7;
    private javax.swing.ButtonGroup pre8;
    private javax.swing.ButtonGroup pre9;
    private javax.swing.JRadioButton ra1;
    private javax.swing.JRadioButton ra10;
    private javax.swing.JRadioButton ra11;
    private javax.swing.JRadioButton ra12;
    private javax.swing.JRadioButton ra13;
    private javax.swing.JRadioButton ra14;
    private javax.swing.JRadioButton ra15;
    private javax.swing.JRadioButton ra16;
    private javax.swing.JRadioButton ra17;
    private javax.swing.JRadioButton ra18;
    private javax.swing.JRadioButton ra19;
    private javax.swing.JRadioButton ra2;
    private javax.swing.JRadioButton ra20;
    private javax.swing.JRadioButton ra21;
    private javax.swing.JRadioButton ra22;
    private javax.swing.JRadioButton ra23;
    private javax.swing.JRadioButton ra24;
    private javax.swing.JRadioButton ra25;
    private javax.swing.JRadioButton ra26;
    private javax.swing.JRadioButton ra27;
    private javax.swing.JRadioButton ra28;
    private javax.swing.JRadioButton ra29;
    private javax.swing.JRadioButton ra3;
    private javax.swing.JRadioButton ra30;
    private javax.swing.JRadioButton ra31;
    private javax.swing.JRadioButton ra32;
    private javax.swing.JRadioButton ra33;
    private javax.swing.JRadioButton ra34;
    private javax.swing.JRadioButton ra35;
    private javax.swing.JRadioButton ra36;
    private javax.swing.JRadioButton ra37;
    private javax.swing.JRadioButton ra38;
    private javax.swing.JRadioButton ra39;
    private javax.swing.JRadioButton ra4;
    private javax.swing.JRadioButton ra40;
    private javax.swing.JRadioButton ra41;
    private javax.swing.JRadioButton ra42;
    private javax.swing.JRadioButton ra43;
    private javax.swing.JRadioButton ra44;
    private javax.swing.JRadioButton ra45;
    private javax.swing.JRadioButton ra46;
    private javax.swing.JRadioButton ra47;
    private javax.swing.JRadioButton ra48;
    private javax.swing.JRadioButton ra49;
    private javax.swing.JRadioButton ra5;
    private javax.swing.JRadioButton ra50;
    private javax.swing.JRadioButton ra51;
    private javax.swing.JRadioButton ra52;
    private javax.swing.JRadioButton ra53;
    private javax.swing.JRadioButton ra54;
    private javax.swing.JRadioButton ra55;
    private javax.swing.JRadioButton ra56;
    private javax.swing.JRadioButton ra57;
    private javax.swing.JRadioButton ra58;
    private javax.swing.JRadioButton ra59;
    private javax.swing.JRadioButton ra6;
    private javax.swing.JRadioButton ra60;
    private javax.swing.JRadioButton ra61;
    private javax.swing.JRadioButton ra62;
    private javax.swing.JRadioButton ra63;
    private javax.swing.JRadioButton ra64;
    private javax.swing.JRadioButton ra65;
    private javax.swing.JRadioButton ra66;
    private javax.swing.JRadioButton ra67;
    private javax.swing.JRadioButton ra68;
    private javax.swing.JRadioButton ra69;
    private javax.swing.JRadioButton ra7;
    private javax.swing.JRadioButton ra70;
    private javax.swing.JRadioButton ra71;
    private javax.swing.JRadioButton ra72;
    private javax.swing.JRadioButton ra73;
    private javax.swing.JRadioButton ra74;
    private javax.swing.JRadioButton ra75;
    private javax.swing.JRadioButton ra76;
    private javax.swing.JRadioButton ra77;
    private javax.swing.JRadioButton ra78;
    private javax.swing.JRadioButton ra79;
    private javax.swing.JRadioButton ra8;
    private javax.swing.JRadioButton ra80;
    private javax.swing.JRadioButton ra81;
    private javax.swing.JRadioButton ra9;
    private javax.swing.JTextField txtNumeroId;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables


private void contarRespuetas(){
    this.respuetasLinguistica = 0;
    this.respuetasMatematicas = 0;
    this.validarRespuesta(pregunta1);
    this.validarRespuesta(pregunta2);
    this.validarRespuesta(pregunta3);
    this.validarRespuesta(pregunta4);
    this.validarRespuesta(pregunta5);
    this.validarRespuesta(pregunta6);
    this.validarRespuesta(pregunta7);
    this.validarRespuesta(pregunta8);
    this.validarRespuesta(pregunta9);
    this.validarRespuesta(pregunta10);
    this.validarRespuesta(pregunta11);
    this.validarRespuesta(pregunta12);
    this.validarRespuesta(pregunta13);
    this.validarRespuesta(pregunta14);
    this.validarRespuesta(pregunta15);
    this.validarRespuesta(pregunta16);
    
  
}

private void validarRespuesta( Pregunta pregunta ){
    if (pregunta.getValorInsertado()==null){
        return;
    }
    if (pregunta.getValorInsertado().equals(pregunta.getRespuesta())){
        if(pregunta.getTipo().equals("Linguistica")){
            respuetasLinguistica = respuetasLinguistica+1;
        }
        else{
            respuetasMatematicas = respuetasMatematicas+1;
        }
    }
}

}
